ecmaFeatures:
  jsx: true
  modules: true

env:
  browser: true
  es6: true
  node: true

extends:
  - eslint:recommended
  - plugin:flowtype/recommended
  - plugin:react/recommended

parser: babel-eslint

plugins:
  - flowtype
  - react

root: true

rules:
  eqeqeq: error
  no-console: warn
  no-var: error
  prefer-const: error
  flowtype/no-types-missing-file-annotation: [0]
